import jax
import numpy as np
import pytest

from dicode.e3_litesim.data import lightweight_rollout as lr
from dicode.e3_litesim.learning.ppo_bridge import (OnPolicyViolation,
                                                   PPOBridge, PPOConfig)
from dicode.e3_litesim.runtime.hashing import hash_pytree
from helpers import make_setup


def _batch(s, params):
    rng = jax.random.PRNGKey(0)
    keys = jax.random.split(rng, 2)
    _o, state0 = lr.batched_reset(s["env"], s["env_params"], keys)
    mem = {k: np.asarray(v) for k, v in
           s["backend"].init_runner_memory(2).items()}
    return lr.collect_rollouts(env=s["env"], env_params=s["env_params"],
                               backend=s["backend"], params=params,
                               start_states=[state0], start_memories=[mem],
                               horizon=6, rng=rng, deterministic=False,
                               collect_trace=False)


def test_update_and_on_policy_enforced():
    s = make_setup()
    bridge = PPOBridge(s["backend"], PPOConfig(update_epochs=1))
    ts = bridge.create_train_state(s["params"], jax.random.PRNGKey(0))
    batch = _batch(s, ts.params)
    before = hash_pytree(ts.params)
    ts2, metrics = bridge.update(ts, [batch], jax.random.PRNGKey(1))
    after = hash_pytree(ts2.params)
    assert after != before
    assert np.isfinite(metrics["p_loss"]) and np.isfinite(metrics["v_loss"])

    stale = _batch(s, s["params"])  # generated by a different policy
    with pytest.raises(OnPolicyViolation):
        bridge.update(ts2, [stale], jax.random.PRNGKey(2))