"""PPOBridge: canonical PPO objective over externally collected on-policy
short-rollout batches, through the backend ABC (policy_forward_eval).

ppo_tr.py stays byte-identical (baseline compatibility).  Recurrent students
are handled sequence-wise: minibatches split the ENV axis, time stays
sequential, and every sequence recomputes from its captured entering memory
(SlowGRU longstate included).  G5: a batch whose policy_hash differs from the
current TrainState params is rejected (no off-policy replay as main data).
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, List

import jax
import jax.numpy as jnp
import numpy as np
import optax

from ..runtime.hashing import hash_pytree


class OnPolicyViolation(RuntimeError):
    """Training batch was generated by a different policy (fail closed)."""


@dataclass
class PPOConfig:
    lr: float = 3e-4
    update_epochs: int = 4
    num_minibatches: int = 1
    gamma: float = 0.99
    gae_lambda: float = 0.95
    clip_eps: float = 0.2
    ent_coef: float = 0.01
    vf_coef: float = 0.5
    max_grad_norm: float = 0.5


class PPOBridge:
    def __init__(self, backend, config: PPOConfig = PPOConfig()) -> None:
        self.backend = backend
        self.config = config
        self.tx = optax.chain(
            optax.clip_by_global_norm(config.max_grad_norm),
            optax.adam(config.lr, eps=1e-5))

    def create_train_state(self, params, rng):
        return self.backend.create_train_state_from_checkpoint(params, self.tx, rng)

    # ------------------------------------------------------------------
    def _prepare(self, batch) -> dict:
        obs = jnp.asarray(batch.obs)
        actions = jnp.asarray(batch.actions)
        rewards = jnp.asarray(batch.rewards)
        dones = jnp.asarray(batch.dones)
        old_logp = jnp.asarray(batch.old_logp)
        old_value = jnp.asarray(batch.old_value)
        bootstrap = jnp.asarray(batch.bootstrap_value)
        cfg = self.config
        t_steps = obs.shape[0]
        adv = jnp.zeros_like(rewards)
        last_gae = jnp.zeros_like(bootstrap)
        for t in reversed(range(t_steps)):
            next_value = jnp.where(t == t_steps - 1, bootstrap, old_value[t + 1])
            nonterm = 1.0 - dones[t]
            delta = (rewards[t] + cfg.gamma * next_value * nonterm - old_value[t])
            last_gae = delta + cfg.gamma * cfg.gae_lambda * nonterm * last_gae
            adv = adv.at[t].set(last_gae)
        returns = adv + old_value
        return {"obs": obs, "actions": actions, "old_logp": old_logp,
                "old_value": old_value, "adv": adv, "returns": returns,
                "entering_memory": jax.tree_util.tree_map(jnp.asarray,
                                                          batch.entering_memory)}

    def _sequence_loss(self, params, prep, env_idx, agg):
        backend = self.backend
        obs = prep["obs"][:, env_idx]
        actions = prep["actions"][:, env_idx]
        old_logp = prep["old_logp"][:, env_idx]
        adv = prep["adv"][:, env_idx]
        returns = prep["returns"][:, env_idx]
        mem0 = jax.tree_util.tree_map(lambda x: x[env_idx], prep["entering_memory"])

        def step(mem, inputs):
            obs_t, act_t = inputs
            pi, value, _mo, new_mem = backend.policy_forward_eval(
                params, mem, obs_t)
            logp = pi.log_prob(act_t)
            ent = pi.entropy()
            return new_mem, (logp, value, ent)

        (_mem_out), (logp, value, ent) = jax.lax.scan(
            step, mem0, (obs, actions))
        ratio = jnp.exp(logp - old_logp)
        adv_n = (adv - adv.mean()) / (adv.std() + 1e-8)
        actor = -jnp.minimum(ratio * adv_n,
                             jnp.clip(ratio, 1 - self.config.clip_eps,
                                      1 + self.config.clip_eps) * adv_n).mean()
        v_loss = jnp.square(value - returns).mean()
        entropy = ent.mean()
        loss = actor + self.config.vf_coef * v_loss - self.config.ent_coef * entropy
        return loss, (actor, v_loss, entropy)

    def update(self, train_state, batches: List, rng) -> tuple:
        cfg = self.config
        current_hash = hash_pytree(train_state.params)
        for batch in batches:
            if batch.policy_hash != current_hash:
                raise OnPolicyViolation(
                    f"G5 ON_POLICY violation: batch policy {batch.policy_hash[:12]} "
                    f"!= current student {current_hash[:12]}; discard stale batch")
        preps = [self._prepare(b) for b in batches]
        metrics = {"ppo_updates": 0.0}
        for _epoch in range(cfg.update_epochs):
            rng, perm_key, mb_key = jax.random.split(rng, 3)
            sizes = [p["obs"].shape[1] for p in preps]
            for prep, size in zip(preps, sizes):
                order = np.arange(size)
                np_rng = np.random.default_rng(int(jax.random.randint(
                    perm_key, (), 0, 2 ** 31 - 1)))
                np_rng.shuffle(order)
                chunks = np.array_split(order, min(cfg.num_minibatches, size))
                for chunk in chunks:
                    if chunk.size == 0:
                        continue
                    idx = jnp.asarray(chunk.tolist(), dtype=jnp.int32)

                    def loss_fn(params):
                        loss, parts = self._sequence_loss(params, prep, idx, None)
                        return loss, parts

                    grad, (a_l, v_l, e_l) = jax.grad(
                        loss_fn, has_aux=True)(train_state.params)
                    g_norm = optax.global_norm(grad)
                    train_state = train_state.apply_gradients(grads=grad)
                    metrics = {
                        "p_loss": float(a_l), "v_loss": float(v_l),
                        "entropy": float(e_l), "grad_norm": float(g_norm),
                        "ppo_updates": metrics["ppo_updates"] + 1.0,
                    }
        return train_state, metrics