"""Typed, provenance-safe primitives for simulator-centric frontier work.

This package is intentionally a foundation layer.  It does not start PPO,
call an LLM, execute branch rollouts, or claim training/evaluation results.
"""

from .goals import (
    AchievementGoal,
    CompositeGoal,
    GateProgressGoal,
    GoalEvaluation,
    GoalSpec,
    StateFact,
    StateFactsGoal,
    TerminalEventGoal,
    Comparison,
    GoalStatus,
    goal_hash,
    evaluate_goal,
)
from .terminal_events import TerminalEventAdapter, TerminalTransition
from .state_codec import EncodedState, StateBundle, StateCodec
from .archive_schema import FrontierArchiveEntry
from .frontier_archive import PRODUCTION_SCHEMA_VERSION, FrontierArchive
from .archive_guards import (
    ARCHIVE_PRODUCTION_WRITE_READY,
    ENTRY_PROVENANCE_SCHEMA,
    TEST_FIXTURE_CAPTURE_REASON_PREFIX,
    compute_entry_provenance_hash,
    finalize_entry_provenance,
    verify_production_entry,
    verify_test_fixture_entry,
)
from .errors import (
    ArchiveWriteGuardError,
    BranchSearchBlockedError,
    InvalidEvidenceError,
    ProductionBlockedError,
    ProvenanceViolationError,
    SchemaMismatchError,
    SimulatorFrontierError,
)
from .search_statistics import (
    BranchOutcome,
    FeasibilityEstimate,
    SOURCE_ESTIMATE_VERSION,
    SourceFeasibilityEstimate,
    estimate_feasibility,
    estimate_feasibility_by_source,
)
from .memory_modes import (
    MemoryCompatibilityReport,
    MemoryRestoreMode,
    MemoryRestoreRequest,
    MemoryRestoreResult,
    validate_memory_request,
)
from .provenance import (
    DataSource,
    FormalDataLeakageGuard,
    SearchActionLeakageGuard,
)
from .discovery_provenance import (
    BLOCKED_WAITING_FROZEN_FORMAL_ASSET_REGISTRY,
    DISCOVERY_FORMAL_PROVENANCE_ISOLATED,
    DISCOVERY_PROVENANCE_CONTRACT_READY,
    FROZEN_FORMAL_ASSET_REGISTRY_BOUND,
    REGISTRY_USAGE_PRODUCTION,
    REGISTRY_USAGE_TEST_ONLY,
    AssetKind,
    CaptureProvenance,
    DiscoveryAssetRecord,
    DiscoveryProvenance,
    DiscoveryProvenanceRegistry,
    FormalAssetIdentity,
    assert_not_formal,
    clear_injected_production_registry,
    discovery_source_for,
    inject_frozen_formal_asset_registry,
    production_registry,
    production_registry_bound,
    registry_hash_of,
    registry_status,
    validate_capture_provenance,
    validate_capture_provenance_production,
    validate_discovery_registry,
)
from .student_binding import (
    REQUIRED_ENTRY_BINDING_FIELDS,
    UNBOUND_STUDENT,
    assert_entry_bound,
    assert_outcome_bound,
    bind_branch_outcome,
    bind_capture_entry,
    check_bound_entry_memory_request,
)
from .combined_restore_contract import (
    CALLBACK_DRIVER_IS_CONTRACT_ONLY,
    CROSS_CHECKS,
    REQUIRED_COMPONENTS,
    CombinedRestoreRequest,
    CombinedRestoreVerdict,
    ComponentResult,
    ComponentStatus,
    evaluate_verdict,
    run_combined_restore,
)
from .fresh_process_restore import (
    BLOCKED_WAITING_CONTROLLER_SIGNED_REGISTRY_BUNDLE,
    BUNDLE_SCHEMA,
    COMBINED_FRESH_PROCESS_RESTORE_EXECUTED,
    CONTROLLER_SIGNED_REGISTRY_BUNDLE_BOUND,
    FRESH_PROCESS_DRIVER_CONTRACT_READY,
    OPTIMIZER_ORIGIN_CHECKPOINT,
    OPTIMIZER_ORIGIN_TX_INIT,
    PRODUCTION_REGISTRY_BUNDLE_CONTRACT_READY,
    SYNTHETIC_FIXTURE_LABEL,
    SYNTHETIC_SIGNATURE_PREFIX,
    ComponentArtifactSpec,
    ComponentLeafEvidence,
    FreshProcessRestoreOutcome,
    FreshProcessRestoreRequest,
    LeafRecord,
    LoaderEntryPoint,
    ProcessEvidence,
    ProductionRegistryBundle,
    ReplayEvidence,
    leaves_digest_of,
    load_evidence_payload,
    production_joint_pass,
    run_fresh_process_restore,
    run_fresh_process_restore_production,
    synthetic_replay_digest,
    tree_leaf_records,
    treedef_of,
    verdict_from_evidence,
    verify_controller_signature,
    verify_fresh_process_evidence,
)
from .verified_restore_context import (
    VERIFIED_RESTORE_CONTEXT_SCHEMA,
    VERIFIER_HASH,
    VERIFIER_ID,
    VerifiedRestoreContext,
    compute_context_hash,
    mint_verified_restore_context,
    process_evidence_hash_of,
    restore_request_hash_of,
    verify_verified_restore_context,
    verdict_hash_of,
)
from .branch_search_runner import (
    RESTORE_CONTEXT_DRIVER,
    RUNNER_VERSION,
    SEARCH_SOURCES,
    SEARCH_SOURCE_REFERENCE_POLICY,
    SEARCH_SOURCE_STUDENT_DETERMINISTIC,
    SEARCH_SOURCE_STUDENT_STOCHASTIC,
    BranchSearchRunConfig,
    BranchSearchRunner,
    MemoryArtifactRef,
    actual_n_summary,
    derive_branch_seeds,
    require_production_restore_context,
)
from .invocation_gate import (
    LLM_ROLE_SEQUENCE,
    FakeLLMClient,
    InvocationContractError,
    InvocationDecision,
    InvocationReason,
    SelectionResult,
    assert_never_exactly_one_call,
    build_aggregate_evidence,
    decide_invocation,
    deterministic_select,
    evidence_hash_of,
    run_two_llm_gate,
)
from .llm_contracts import (
    DIAGNOSTICIAN_FIELDS,
    DIAGNOSTICIAN_OUTPUT_SCHEMA,
    FRONTIER_CLASSES,
    JOURNAL_CHAIN_SEED,
    PLANNER_FIELDS,
    PLANNER_OUTPUT_SCHEMA,
    PLANNER_SEARCH_SOURCES,
    REAL_TWO_LLM_BLOCKED_NO_AUTHORIZED_CLIENT,
    TWO_LLM_AUTHORIZATION_SCHEMA,
    TWO_LLM_CALL_CEILING,
    AuthorizedTwoLLMRuntime,
    CallJournal,
    CallJournalEntry,
    DiagnosticianOutput,
    LLMContractError,
    PlannerOutput,
    TwoLLMAuthorization,
    assert_planner_output_bound,
    compute_diagnostician_hash,
    compute_planner_hash,
    derive_invocation_from_evidence,
    mint_two_llm_authorization,
    run_two_llm_production,
    run_typed_two_llm_gate,
    verify_two_llm_authorization,
    validate_diagnostician_output,
    validate_planner_output,
)
from .feasibility_classifier import (
    CLASSIFICATION_VERSION,
    FrontierClass,
    FrontierClassification,
    classify_frontier,
)
from .evidence_selector import (
    FRONTIER_START_WEIGHTS,
    MIN_BUCKET_DIVERSITY,
    PRODUCTION_MEMORY_STATUSES,
    SELECTION_EVIDENCE_SCHEMA,
    SELECTOR_VERSION,
    STUDENT_DOMINANCE_GAP_THRESHOLD,
    EvidenceSelectionResult,
    SelectionEvidence,
    evidence_based_select,
    mint_selection_evidence_from_outcomes,
    verify_selection_evidence,
)
from .frontier_distributions import (
    DISTRIBUTION_SCHEMA,
    DISTRIBUTION_SLOT_IDS,
    PLANNER_COMPILER_VERSION,
    FrontierDistribution,
    FrontierDistributionPlan,
    PlannerCompilation,
    compile_planner_to_frontier_distributions,
    compose_12_plus_4,
    validate_frontier_distribution_plan,
)
from .distribution_runtime import (
    DISTRIBUTION_RUNTIME_VERSION,
    DistributionRuntimeBinding,
    resolve_distribution_binding,
    verify_distribution_binding,
)
from .training_runtime import (
    BLOCKED_NO_BOUND_ORIGINAL_TRAINING_RUNTIME,
    TRAINING_RUNTIME_VERSION,
    OriginalTrainingRuntime,
    mint_original_training_runtime,
    runtime_binding_summary,
    verify_original_training_runtime,
)
from .optimizer_attestation import (
    BLOCKED_OPTIMIZER_STEP_BASELINE_UNMEASURED,
    OPTIMIZER_ATTESTATION_VERSION,
    OptimizerUpdateAttestation,
    attestation_fields,
    mint_optimizer_update_attestation,
    verify_optimizer_update_attestation,
)
from .round_trip_evidence import (
    RESTORE_DRIVER_IN_PROCESS_ADAPTER,
    ROUND_TRIP_EVIDENCE_VERSION,
    CheckpointRoundTripEvidence,
    measure_replay_equivalence,
    mint_checkpoint_round_trip_evidence,
    verify_checkpoint_round_trip_evidence,
)
from .surface_capability import (
    BLOCKED_NO_SIGNED_TRAINING_SURFACE_CAPABILITY,
    SURFACE_CAPABILITY_VERSION,
    TrainingSurfaceCapability,
    mint_training_surface_capability,
    verify_training_surface_capability,
)
from .anchor_manifest import (
    ANCHOR_SLOT_COUNT,
    BLOCKED_SHARED_ANCHOR_MANIFEST,
    DYNAMIC_DISTRIBUTION_COUNT,
    SHARED_ANCHOR_MANIFEST_BOUND,
    AnchorDefinition,
    AnchorManifest,
    RetentionContract,
    bind_anchor_manifest,
    manifest_hash_of,
    unbound_status,
    validate_anchor_manifest,
)
from .e3_window import (
    BLOCKED_TRAINING_SURFACE_PENDING_R9,
    CHECKPOINT_RELOAD,
    E3_WINDOW_SCHEMA,
    E3_WINDOW_STEPS,
    PREFLIGHT_VERSION,
    REAL_ACTUAL_N_EXECUTED,
    REAL_ONE_UPDATE_EXECUTED,
    REAL_TWO_LLM_EXECUTED,
    E3PreflightResult,
    E3WindowConfig,
    one_window_pipeline,
    run_e3_preflight,
)

__all__ = [
    "AchievementGoal", "CompositeGoal", "GateProgressGoal", "GoalEvaluation",
    "GoalSpec", "StateFact", "StateFactsGoal", "TerminalEventGoal", "Comparison", "GoalStatus",
    "goal_hash", "evaluate_goal",
    "TerminalEventAdapter", "TerminalTransition", "EncodedState", "StateBundle",
    "StateCodec", "FrontierArchiveEntry", "FrontierArchive",
    "PRODUCTION_SCHEMA_VERSION",
    "ARCHIVE_PRODUCTION_WRITE_READY", "ENTRY_PROVENANCE_SCHEMA",
    "TEST_FIXTURE_CAPTURE_REASON_PREFIX",
    "compute_entry_provenance_hash", "finalize_entry_provenance",
    "verify_production_entry", "verify_test_fixture_entry",
    "ArchiveWriteGuardError", "BranchSearchBlockedError", "InvalidEvidenceError",
    "ProductionBlockedError", "ProvenanceViolationError", "SchemaMismatchError",
    "SimulatorFrontierError",
    "BranchOutcome",
    "VERIFIED_RESTORE_CONTEXT_SCHEMA", "VERIFIER_HASH", "VERIFIER_ID",
    "VerifiedRestoreContext", "compute_context_hash",
    "mint_verified_restore_context", "process_evidence_hash_of",
    "restore_request_hash_of", "verify_verified_restore_context",
    "verdict_hash_of",
    "RESTORE_CONTEXT_DRIVER", "RUNNER_VERSION", "SEARCH_SOURCES",
    "SEARCH_SOURCE_REFERENCE_POLICY", "SEARCH_SOURCE_STUDENT_DETERMINISTIC",
    "SEARCH_SOURCE_STUDENT_STOCHASTIC",
    "BranchSearchRunConfig", "BranchSearchRunner", "MemoryArtifactRef",
    "actual_n_summary", "derive_branch_seeds", "require_production_restore_context",
    "FeasibilityEstimate", "SOURCE_ESTIMATE_VERSION", "SourceFeasibilityEstimate",
    "estimate_feasibility", "estimate_feasibility_by_source",
    "MemoryCompatibilityReport",
    "MemoryRestoreMode", "MemoryRestoreRequest", "MemoryRestoreResult", "validate_memory_request", "DataSource",
    "FormalDataLeakageGuard", "SearchActionLeakageGuard",
    "BLOCKED_WAITING_FROZEN_FORMAL_ASSET_REGISTRY",
    "DISCOVERY_FORMAL_PROVENANCE_ISOLATED", "DISCOVERY_PROVENANCE_CONTRACT_READY",
    "FROZEN_FORMAL_ASSET_REGISTRY_BOUND",
    "REGISTRY_USAGE_PRODUCTION", "REGISTRY_USAGE_TEST_ONLY",
    "AssetKind", "CaptureProvenance", "DiscoveryAssetRecord", "DiscoveryProvenance",
    "DiscoveryProvenanceRegistry", "FormalAssetIdentity", "assert_not_formal",
    "clear_injected_production_registry", "discovery_source_for",
    "inject_frozen_formal_asset_registry", "production_registry",
    "production_registry_bound", "registry_hash_of", "registry_status",
    "validate_capture_provenance", "validate_capture_provenance_production",
    "validate_discovery_registry",
    "REQUIRED_ENTRY_BINDING_FIELDS", "UNBOUND_STUDENT", "assert_entry_bound",
    "assert_outcome_bound", "bind_branch_outcome", "bind_capture_entry",
    "check_bound_entry_memory_request",
    "CALLBACK_DRIVER_IS_CONTRACT_ONLY",
    "CROSS_CHECKS", "REQUIRED_COMPONENTS", "CombinedRestoreRequest",
    "CombinedRestoreVerdict", "ComponentResult", "ComponentStatus",
    "evaluate_verdict", "run_combined_restore",
    "BLOCKED_WAITING_CONTROLLER_SIGNED_REGISTRY_BUNDLE", "BUNDLE_SCHEMA",
    "COMBINED_FRESH_PROCESS_RESTORE_EXECUTED", "CONTROLLER_SIGNED_REGISTRY_BUNDLE_BOUND",
    "FRESH_PROCESS_DRIVER_CONTRACT_READY",
    "OPTIMIZER_ORIGIN_CHECKPOINT", "OPTIMIZER_ORIGIN_TX_INIT",
    "PRODUCTION_REGISTRY_BUNDLE_CONTRACT_READY",
    "SYNTHETIC_FIXTURE_LABEL", "SYNTHETIC_SIGNATURE_PREFIX",
    "ComponentArtifactSpec", "ComponentLeafEvidence", "FreshProcessRestoreOutcome",
    "FreshProcessRestoreRequest", "LeafRecord", "LoaderEntryPoint", "ProcessEvidence",
    "ProductionRegistryBundle", "ReplayEvidence",
    "leaves_digest_of", "load_evidence_payload",
    "production_joint_pass",
    "run_fresh_process_restore", "run_fresh_process_restore_production",
    "synthetic_replay_digest", "tree_leaf_records", "treedef_of",
    "verdict_from_evidence", "verify_controller_signature",
    "verify_fresh_process_evidence",
    "LLM_ROLE_SEQUENCE", "FakeLLMClient", "InvocationContractError",
    "InvocationDecision", "InvocationReason", "SelectionResult",
    "assert_never_exactly_one_call", "build_aggregate_evidence",
    "decide_invocation", "deterministic_select", "evidence_hash_of",
    "run_two_llm_gate",
    "DIAGNOSTICIAN_FIELDS", "DIAGNOSTICIAN_OUTPUT_SCHEMA", "FRONTIER_CLASSES",
    "PLANNER_FIELDS", "PLANNER_OUTPUT_SCHEMA", "PLANNER_SEARCH_SOURCES",
    "REAL_TWO_LLM_BLOCKED_NO_AUTHORIZED_CLIENT",
    "JOURNAL_CHAIN_SEED", "TWO_LLM_AUTHORIZATION_SCHEMA", "TWO_LLM_CALL_CEILING",
    "AuthorizedTwoLLMRuntime", "CallJournal", "CallJournalEntry",
    "TwoLLMAuthorization",
    "DiagnosticianOutput", "LLMContractError", "PlannerOutput",
    "assert_planner_output_bound", "compute_diagnostician_hash",
    "compute_planner_hash", "derive_invocation_from_evidence",
    "mint_two_llm_authorization", "verify_two_llm_authorization",
    "run_two_llm_production", "run_typed_two_llm_gate",
    "validate_diagnostician_output", "validate_planner_output",
    "CLASSIFICATION_VERSION", "FrontierClass", "FrontierClassification",
    "classify_frontier",
    "FRONTIER_START_WEIGHTS", "MIN_BUCKET_DIVERSITY", "PRODUCTION_MEMORY_STATUSES",
    "SELECTION_EVIDENCE_SCHEMA", "SELECTOR_VERSION", "STUDENT_DOMINANCE_GAP_THRESHOLD",
    "EvidenceSelectionResult", "SelectionEvidence", "evidence_based_select",
    "mint_selection_evidence_from_outcomes", "verify_selection_evidence",
    "DISTRIBUTION_SCHEMA", "DISTRIBUTION_SLOT_IDS", "PLANNER_COMPILER_VERSION",
    "FrontierDistribution", "FrontierDistributionPlan", "PlannerCompilation",
    "compile_planner_to_frontier_distributions",
    "compose_12_plus_4", "validate_frontier_distribution_plan",
    "DISTRIBUTION_RUNTIME_VERSION", "DistributionRuntimeBinding",
    "resolve_distribution_binding", "verify_distribution_binding",
    "BLOCKED_NO_BOUND_ORIGINAL_TRAINING_RUNTIME", "TRAINING_RUNTIME_VERSION",
    "OriginalTrainingRuntime", "mint_original_training_runtime",
    "runtime_binding_summary", "verify_original_training_runtime",
    "BLOCKED_OPTIMIZER_STEP_BASELINE_UNMEASURED", "OPTIMIZER_ATTESTATION_VERSION",
    "OptimizerUpdateAttestation", "attestation_fields",
    "mint_optimizer_update_attestation", "verify_optimizer_update_attestation",
    "RESTORE_DRIVER_IN_PROCESS_ADAPTER", "ROUND_TRIP_EVIDENCE_VERSION",
    "CheckpointRoundTripEvidence", "measure_replay_equivalence",
    "mint_checkpoint_round_trip_evidence", "verify_checkpoint_round_trip_evidence",
    "BLOCKED_NO_SIGNED_TRAINING_SURFACE_CAPABILITY", "SURFACE_CAPABILITY_VERSION",
    "TrainingSurfaceCapability", "mint_training_surface_capability",
    "verify_training_surface_capability",
    "ANCHOR_SLOT_COUNT", "BLOCKED_SHARED_ANCHOR_MANIFEST",
    "DYNAMIC_DISTRIBUTION_COUNT", "SHARED_ANCHOR_MANIFEST_BOUND",
    "AnchorDefinition", "AnchorManifest", "RetentionContract",
    "bind_anchor_manifest", "manifest_hash_of", "unbound_status",
    "validate_anchor_manifest",
    "BLOCKED_TRAINING_SURFACE_PENDING_R9", "CHECKPOINT_RELOAD",
    "E3_WINDOW_SCHEMA", "E3_WINDOW_STEPS", "PREFLIGHT_VERSION",
    "REAL_ACTUAL_N_EXECUTED", "REAL_ONE_UPDATE_EXECUTED",
    "REAL_TWO_LLM_EXECUTED", "E3PreflightResult", "E3WindowConfig",
    "one_window_pipeline", "run_e3_preflight",
]
