"""Result-blind HO capture bank: generation, persistence, loading.

NEG26-isomorphic discipline (same shape as the frozen tier3 state bank):

* captures are generated by a DECLARED capture policy whose seed schedule is
  fixed and independent of every measured student;
* the bank manifest carries NO candidate/student identity of any kind;
* the same bank is shared byte-wise by all arms;
* every payload is hash-bound; loading recomputes all hashes and fails closed
  on any drift.

SYNTHETIC generator is stdlib-only (random.Random) and stamps every artifact
SYNTHETIC_TEST_ONLY. The REAL capture path (server) starts from the
materialized FRONT_L2 state bank with a fixed rollout capture policy; see the
RUNBOOK in docs/memory_study/HO_FLOOR23_DESIGN.md.
"""
from __future__ import annotations

import dataclasses
import json
import random
from pathlib import Path
from typing import List, Tuple

from .ho_contract import (
    SCHEMA_ID_CONTRACT,
    FailClosed,
    HistoryCapture,
    canonical_json_bytes,
    sha256_hex,
)

SCHEMA_ID_BANK = "mechanism_UED.memory_study_capture_bank/v1"
CAPTURE_POLICY_SYNTHETIC = "UNIFORM_RANDOM_SYNTHETIC_V1"
GENERATOR_SYNTHETIC = "SYNTHETIC_TEST_ONLY"
CAPTURE_ID_PREFIX_SYNTHETIC = "SYN"

#: The manifest/capture payloads must never mention measured identities.
FORBIDDEN_BANK_TOKENS = ("candidate", "student")


def _require_forbidden_absent(text: str, where: str) -> None:
    low = text.lower()
    for tok in FORBIDDEN_BANK_TOKENS:
        if tok in low:
            raise FailClosed(
                "RESULT_BLIND_VIOLATION: token %r present in %s" % (tok, where))


def _payload_sha(capture_id: str, obs_segment, source_seed: int,
                 capture_policy_id: str, floor_context: int,
                 timestep_start: int) -> str:
    form = {
        "capture_id": capture_id,
        "obs_segment": [list(row) for row in obs_segment],
        "source_seed": int(source_seed),
        "capture_policy_id": capture_policy_id,
        "floor_context": int(floor_context),
        "timestep_start": int(timestep_start),
    }
    return sha256_hex(canonical_json_bytes(form))


def generate_synthetic_capture_bank(num_captures: int, segment_len: int,
                                    obs_dim: int, seed: int,
                                    floor_context: int = 2,
                                    capture_policy_id: str = CAPTURE_POLICY_SYNTHETIC
                                    ) -> Tuple[dict, List[HistoryCapture]]:
    """Deterministic SYNTHETIC_TEST_ONLY bank. Same seed -> byte-identical bank.

    Values are uniform-random floats rounded to 6 decimals (JSON-stable).
    """
    if num_captures <= 0 or segment_len <= 0 or obs_dim <= 0:
        raise FailClosed("BANK_GEOMETRY_INVALID: num_captures/segment_len/"
                         "obs_dim must all be positive")
    entries = []
    captures: List[HistoryCapture] = []
    for i in range(num_captures):
        capture_id = "%s%04d" % (CAPTURE_ID_PREFIX_SYNTHETIC, i)
        source_seed = seed + i
        row_rng = random.Random(source_seed)
        segment = tuple(
            tuple(round(row_rng.random(), 6) for _ in range(obs_dim))
            for _ in range(segment_len))
        payload_sha = _payload_sha(capture_id, segment, source_seed,
                                   capture_policy_id, floor_context, 0)
        entries.append({
            "capture_id": capture_id,
            "source_seed": int(source_seed),
            "payload_sha256": payload_sha,
        })
        captures.append(HistoryCapture(
            capture_id=capture_id,
            obs_segment=segment,
            source_seed=source_seed,
            capture_policy_id=capture_policy_id,
            bank_hash="",  # bound below once bank_sha256 exists
            payload_sha256=payload_sha,
            floor_context=floor_context,
            timestep_start=0))
    bank_sha = sha256_hex(canonical_json_bytes({
        "schema_id": SCHEMA_ID_BANK,
        "contract_schema_id": SCHEMA_ID_CONTRACT,
        "generator": GENERATOR_SYNTHETIC,
        "capture_policy_id": capture_policy_id,
        "seed": int(seed),
        "num_captures": int(num_captures),
        "segment_len": int(segment_len),
        "obs_dim": int(obs_dim),
        "floor_context": int(floor_context),
        "captures": entries,
    }))
    manifest = {
        "schema_id": SCHEMA_ID_BANK,
        "contract_schema_id": SCHEMA_ID_CONTRACT,
        "generator": GENERATOR_SYNTHETIC,
        "capture_policy_id": capture_policy_id,
        "seed": int(seed),
        "num_captures": int(num_captures),
        "segment_len": int(segment_len),
        "obs_dim": int(obs_dim),
        "floor_context": int(floor_context),
        "captures": entries,
        "bank_sha256": bank_sha,
    }
    _require_forbidden_absent(json.dumps(manifest, sort_keys=True), "manifest")
    captures = [dataclasses.replace(c, bank_hash=bank_sha) for c in captures]
    return manifest, captures


def write_capture_bank(out_dir, manifest: dict,
                       captures: List[HistoryCapture]) -> Path:
    """Write manifest.json + captures/<id>.json + SHA256SUMS under out_dir."""
    out = Path(out_dir)
    cap_dir = out / "captures"
    cap_dir.mkdir(parents=True, exist_ok=True)
    sums = []
    manifest_bytes = canonical_json_bytes(manifest)
    (out / "manifest.json").write_bytes(manifest_bytes)
    sums.append("%s  manifest.json" % sha256_hex(manifest_bytes))
    for cap in captures:
        payload = canonical_json_bytes(cap.payload_form())
        rel = "captures/%s.json" % cap.capture_id
        (cap_dir / ("%s.json" % cap.capture_id)).write_bytes(payload)
        sums.append("%s  %s" % (sha256_hex(payload), rel))
    (out / "SHA256SUMS").write_text("\n".join(sums) + "\n", encoding="utf-8")
    return out


def load_capture_bank(manifest_path) -> Tuple[dict, List[HistoryCapture]]:
    """Load and fully re-verify a bank. Any hash drift fails closed."""
    mpath = Path(manifest_path)
    if not mpath.is_file():
        raise FailClosed("CAPTURE_BANK_MANIFEST_MISSING: %s" % mpath)
    manifest = json.loads(mpath.read_text(encoding="utf-8"))
    if manifest.get("schema_id") != SCHEMA_ID_BANK:
        raise FailClosed("CAPTURE_BANK_SCHEMA_MISMATCH: %r"
                         % manifest.get("schema_id"))
    _require_forbidden_absent(json.dumps(manifest, sort_keys=True), "manifest")
    claimed_bank_sha = manifest.get("bank_sha256")
    body = {k: v for k, v in manifest.items() if k != "bank_sha256"}
    actual_bank_sha = sha256_hex(canonical_json_bytes(body))
    if claimed_bank_sha != actual_bank_sha:
        raise FailClosed("CAPTURE_BANK_HASH_MISMATCH: claimed=%s actual=%s"
                         % (claimed_bank_sha, actual_bank_sha))
    cap_dir = mpath.parent / "captures"
    captures: List[HistoryCapture] = []
    for entry in manifest.get("captures", []):
        cid = entry.get("capture_id")
        cpath = cap_dir / ("%s.json" % cid)
        if not cpath.is_file():
            raise FailClosed("CAPTURE_PAYLOAD_MISSING: %s" % cpath)
        form = json.loads(cpath.read_text(encoding="utf-8"))
        if form.get("capture_id") != cid:
            raise FailClosed("CAPTURE_ID_MISMATCH: %s" % cpath)
        cap = HistoryCapture(
            capture_id=cid,
            obs_segment=tuple(tuple(float(x) for x in row)
                              for row in form["obs_segment"]),
            source_seed=int(form["source_seed"]),
            capture_policy_id=form["capture_policy_id"],
            bank_hash=claimed_bank_sha,
            payload_sha256=entry.get("payload_sha256", ""),
            floor_context=int(form.get("floor_context", 2)),
            timestep_start=int(form.get("timestep_start", 0)))
        cap.validate()
        if cap.payload_sha256 != entry.get("payload_sha256"):
            raise FailClosed("CAPTURE_ENTRY_HASH_INCONSISTENT: %s" % cid)
        captures.append(cap)
    if not captures:
        raise FailClosed("CAPTURE_BANK_EMPTY")
    return manifest, captures


def assign_capture(captures: List[HistoryCapture], assignment_key: str) -> HistoryCapture:
    """Deterministic result-blind assignment: capture index depends ONLY on the
    assignment key (e.g. state identity), never on measured results."""
    if not captures:
        raise FailClosed("CAPTURE_BANK_EMPTY")
    idx = int(sha256_hex(assignment_key.encode("utf-8")), 16) % len(captures)
    return captures[idx]